services: 
  backend:
    image: ecomerce:latest 
    restart: always 
    ports: 
      - 3334:3333
    environment:
      - DB_HOST=db 
    networks:
      - spring-postgres 
  db:
    image: postgres:10.9
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - spring-postgres 
    environment:
      - POSTGRES_PASSWORD=SENAI
     
    expose:
      - 5432
    ports: 
      - 5432:5432
volumes:
  db-data:
networks:
  spring-postgres:
